### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by bonelifer** [pauleve/mpd-dynamic#1]
```
Traceback (most recent call last):
  File "/home/william/.local/bin/mpd-dynamic", line 5, in <module>
    from mpd_dynamic import main
  File "/home/william/.local/lib/python3.8/site-packages/mpd_dynamic.py", line 24, in <module>
    THRESHOLD = config["playlist"].getint("threshold", THRESHOLD)
  File "/usr/lib/python3.8/configparser.py", line 1303, in get
    return _impl(self._name, option, raw=raw, vars=vars,
  File "/usr/lib/python3.8/configparser.py", line 818, in getint
    return self._get_conv(section, option, int, raw=raw, vars=vars,
  File "/usr/lib/python3.8/configparser.py", line 808, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "/usr/lib/python3.8/configparser.py", line 803, in _get
    return conv(self.get(section, option, **kwargs))
ValueError: invalid literal for int() with base 10: '10 # if the remaining number of tracks is less than threshold, it will trigger recommendations'

```

**Comment by pauleve** [comment]
You should remove comments (starting with #)  in the ~/.config/mpd_dynamicrc file

**Comment by bonelifer** [comment]
Now I get this:
`2022-06-01 08:07:14,878 Calling MPD connect('192.168.1.80', 6600, timeout=None)
Traceback (most recent call last):
  File "/home/william/.local/bin/mpd-dynamic", line 8, in <module>
    sys.exit(main())
  File "/home/william/.local/lib/python3.8/site-packages/mpd_dynamic.py", line 288, in main
    probs = get_probs()
  File "/home/william/.local/lib/python3.8/site-packages/mpd_dynamic.py", line 276, in get_probs
    total = sum(weight.values())
TypeError: unsupported operand type(s) for +: 'int' and 'str'
2022-06-01 08:07:14,920 Calling MPD disconnect()
`

**Comment by pauleve** [comment]
Please paste your config file

**Comment by bonelifer** [comment]
I removed the comments from the copy-paste I did from GitHub, and it fixed it. So it was like you originally thought.  Sorry for not getting back to this earlier, had outpatient laser eye surgery and I was wore out afterwards.
